# Generated by Django 3.1.7 on 2021-04-13 16:54

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("subtitle", models.CharField(blank=True, max_length=128, null=True)),
                ("slug", models.SlugField()),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images/products"
                    ),
                ),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="MRP",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "banner1",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/banners"
                    ),
                ),
                (
                    "banner2",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/banners"
                    ),
                ),
                (
                    "banner3",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/banners"
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="MRP",
                    ),
                ),
                ("order", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Unit",
                "verbose_name_plural": "Product Units",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("message", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="app.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="units",
            field=models.ManyToManyField(related_name="units", to="app.Unit"),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_session", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=0, default=1, max_digits=15),
                ),
                ("is_placed", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.unit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_session", models.CharField(max_length=100)),
                ("order_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("pincode", models.CharField(max_length=10)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("IN", "Out of India"),
                            ("AN", "Andaman and Nicobar Islands"),
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CG", "Chandigarh"),
                            ("CH", "Chhattisgarh"),
                            ("DN", "Dadra and Nagar Haveli"),
                            ("DD", "Daman and Diu"),
                            ("DL", "Delhi"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JK", "Jammu and Kashmir"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("LA", "Ladakh"),
                            ("LD", "Lakshadweep"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OR", "Odisha"),
                            ("PY", "Puducherry"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TS", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UK", "Uttarakhand"),
                            ("WB", "West Bengal"),
                        ],
                        default="KL",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_yet_shipped", "Not Yet Shipped"),
                            ("shipped", "Shipped"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("delivered", "Delivered"),
                        ],
                        default="not_yet_shipped",
                        max_length=100,
                    ),
                ),
                ("items", models.ManyToManyField(to="app.OrderItem")),
            ],
            options={
                "ordering": ("-order_date", "status"),
            },
        ),
    ]
