# Generated by Django 3.1.7 on 2021-04-13 16:54

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("description", tinymce.models.HTMLField()),
                ("address", models.TextField()),
                (
                    "email",
                    models.EmailField(default="info@washingdone.com", max_length=128),
                ),
                ("phone", models.CharField(default="+91 9876 543 210", max_length=128)),
                (
                    "brochure",
                    models.FileField(blank=True, null=True, upload_to="files/brochure"),
                ),
                (
                    "working_hours",
                    models.CharField(
                        default="Mon – Sat : 9:00 am – 7:00 pm", max_length=128
                    ),
                ),
            ],
            options={
                "verbose_name": "About Washingdone",
                "verbose_name_plural": "About Washingdone",
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("subtitle", models.CharField(max_length=128)),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/banners"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("icon", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images/testimonials"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                ("place", models.CharField(blank=True, max_length=120, null=True)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("content", tinymce.models.HTMLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-title",),
            },
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(unique=True)),
                ("media", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Medias",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images/testimonials"
                    ),
                ),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_upto", models.DateTimeField()),
                (
                    "special_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="app.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-available_upto",),
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/blogs"
                    ),
                ),
                ("summary", models.TextField()),
                ("content", tinymce.models.HTMLField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="web.category",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
    ]
